-- MySQL Script generated by MySQL Workbench
-- Sat Jun 19 23:14:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cinedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinedb` DEFAULT CHARACTER SET utf8 ;
USE `cinedb` ;

-- -----------------------------------------------------
-- Table `cinedb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinedb`.`Usuario` (
  `idUsuario` VARCHAR(15) NOT NULL,
  `contrasena` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinedb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinedb`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` VARCHAR(15) NULL,
  `Cedula` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `NumeroTarjeta` VARCHAR(16) NOT NULL,
  `total` FLOAT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cinedb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinedb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinedb`.`Sala` (
  `idSala` INT NOT NULL AUTO_INCREMENT,
  `fila` INT NOT NULL,
  `columna` INT NOT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinedb`.`Pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinedb`.`Pelicula` (
  `idPelicula` VARCHAR(200) NOT NULL,
  `poster` LONGBLOB NOT NULL,
  `duracion` TIME NOT NULL,
  `clasificacion` VARCHAR(3) NOT NULL,
  `estreno` INT NOT NULL,
  PRIMARY KEY (`idPelicula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinedb`.`Funcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinedb`.`Funcion` (
  `idFuncion` INT NOT NULL AUTO_INCREMENT,
  `idPelicula` VARCHAR(200) NOT NULL,
  `idSala` INT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NOT NULL,
  PRIMARY KEY (`idFuncion`),
  INDEX `fk_Funcion_Pelicula1_idx` (`idPelicula` ASC) VISIBLE,
  INDEX `fk_Funcion_Sala1_idx` (`idSala` ASC) VISIBLE,
  CONSTRAINT `fk_Funcion_Pelicula1`
    FOREIGN KEY (`idPelicula`)
    REFERENCES `cinedb`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcion_Sala1`
    FOREIGN KEY (`idSala`)
    REFERENCES `cinedb`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinedb`.`Tiquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinedb`.`Tiquete` (
  `idTiquete` INT NOT NULL AUTO_INCREMENT,
  `idFuncion` INT NOT NULL,
  `idFactura` INT NOT NULL,
  `fila` INT NOT NULL,
  `columna` INT NOT NULL,
  PRIMARY KEY (`idTiquete`),
  INDEX `fk_Tiquete_Funcion1_idx` (`idFuncion` ASC) VISIBLE,
  INDEX `fk_Tiquete_Factura1_idx` (`idFactura` ASC) VISIBLE,
  CONSTRAINT `fk_Tiquete_Funcion1`
    FOREIGN KEY (`idFuncion`)
    REFERENCES `cinedb`.`Funcion` (`idFuncion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tiquete_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `cinedb`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
